name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
        check-latest: true
        cache: true
        cache-dependency-path: |
          **/go.sum
          **/go.mod

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.txt
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: sapk/protoc-gen-openapiv3
        
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
        check-latest: true
        cache: true
        cache-dependency-path: |
          **/go.sum
          **/go.mod

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
        check-latest: true
        cache: true
        cache-dependency-path: |
          **/go.sum
          **/go.mod

    - name: Build
      run: go build -v ./...

    - name: Build for different platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -v ./...
        GOOS=darwin GOARCH=amd64 go build -v ./...
        GOOS=windows GOARCH=amd64 go build -v ./...

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
        check-latest: true
        cache: true
        cache-dependency-path: |
          **/go.sum
          **/go.mod

    - name: Run gosec
      uses: securego/gosec@master
      with:
        args: ./...

    - name: Run govulncheck
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
